#ifndef I2C_MONITOR_CONFIG_H
#define I2C_MONITOR_CONFIG_H

#include <stdint.h>

#define I2C_MONITOR_CHANNEL_COUNT 4u
#define I2C_MONITOR_BUFFER_COUNT 2u
#define I2C_MONITOR_BUFFER_WORDS 64u
#define I2C_MONITOR_DEFAULT_SAMPLE_HZ 8000000u

#define I2C_MONITOR_CHANNEL0_SDA_GPIO 16u
#define I2C_MONITOR_CHANNEL0_SCL_GPIO 17u
#define I2C_MONITOR_CHANNEL1_SDA_GPIO 18u
#define I2C_MONITOR_CHANNEL1_SCL_GPIO 19u
#define I2C_MONITOR_CHANNEL2_SDA_GPIO 20u
#define I2C_MONITOR_CHANNEL2_SCL_GPIO 21u
#define I2C_MONITOR_CHANNEL3_SDA_GPIO 26u
#define I2C_MONITOR_CHANNEL3_SCL_GPIO 27u

#endif